---
title: "Assignment 2 figures"
author: "Brian Dawes"
format: pdf
editor: visual
---

## Assignment 2 Figures:

##Formatting data and setup

```{r setup, message=FALSE, warning=FALSE}
#Downloading/formatting data
library(tidyverse)
library(gtsummary)
library(ggplot2)
cohort <- read.csv("raw-data/cohort.csv")
cohort$smoke <- factor(cohort$smoke, levels = c(0, 1), labels = c("No", "Yes"))
cohort$female <- factor(cohort$female, levels = c(0, 1), labels = c("Male", "Female"))
cohort$cardiac <- factor(cohort$cardiac, levels = c(0, 1), labels = c("No", "Yes"))


```

## Table 1: Descriptive Statistics

```{r descriptive table}
cohort %>%
  tbl_summary(statistic = list(all_continuous() ~ "{mean} ± {sd}")) 
```

## Table 2: Cardiac Disease Prediction Model

```{r cardiac model}

cardiac_model <- glm(cardiac~female + smoke + age, data=cohort, family=binomial)
summary(cardiac_model)
cardiac_model %>%
  tbl_regression(exponentiate = TRUE) %>%
  add_glance_table(include = c(logLik, AIC)) %>%
  modify_caption("Prediction Model for Cardiac Disease")

```

## Table 3: Cost Prediction Model

```{r cost model}
cost_model <- lm(cost ~ female + smoke + age + cardiac, data = cohort)
summary(cost_model)
cost_model %>%
  tbl_regression() %>%
  add_glance_table(include = c(r.squared, AIC)) %>%
  modify_caption("Predictive Model for Healthcare Costs")
```

## Figure 1: Distribution of Costs by Smoking Status

```{r Cost plot}

ggplot(cohort, aes(x=smoke, y=cost)) + geom_violin() + 
  labs(title = "Cost by smoking status", x="smoking status", y="cost") + theme_minimal()

```
